#!/usr/bin/env python
#$ Looks for an aim header and builds index out of it. 

from __future__ import with_statement 
import sys 
import os


def parse(fname, fout):
    try:
        with open(fname) as f:
            for line in f.readlines():
                if line.startswith('#$'):
                    fout.write("%30s  |   %s" %(fname, line.split('$', 1)[1]))
    except:
        return


if __name__ == "__main__":
    full_directory_flag = False
    directory_listing = os.listdir('.')
    fout = open("index.indx",'w')

    try:
        fname = sys.argv[1]
    except IndexError:
        full_directory_flag = True
    if not full_directory_flag:
        try:
            open(fname)
        except:
            print "This file doesn't exist."
        parse(sys.argv[1], fout)
    else:
        # Full directory requested
        # non recursive as of now
        for f in directory_listing:
            parse(f, fout)
    fout.close()

